apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-postgres-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: sonar-postgres-pv
  nfs:
    server: 10.10.50.30
    path: "/mnt/nfs-share/"
